### ISSUE TITLE
How to use with webpack?

### ISSUE THREAD

**Issue by williamoliveira** [pi0/bootstrap-vue#1]
I am using vue cli's webpack template and I tried including bootstrap-vue on the babel loader like this: 
```js
//...
const projectRootPath = path.resolve(__dirname, '../')
const srcPath = path.join(projectRootPath, 'src')
const bootstrapVuePath = path.join(projectRootPath, 'node_modules/bootstrap-vue')
//...
{
     test: /\.js$/,
     loader: 'babel',
     include: [srcPath, bootstrapVueRoot]
},
```
 but it does not works, the files aren't being transpilled, they get imported raw and the browser throws `Uncaught SyntaxError: Unexpected token import`

Am I missing something?

**Comment by pi0** [comment]
@williamoliveira Thanks for your bug report. it seems your current webpack config doesn't transforms ES6 syntax! (why using `include` directive instead of `resolveLoader` option ?) 
furthermore you also need `scss` loader in your config.
 
I'll release bundled dist + demo project tonight for easier usage :)

**Comment by williamoliveira** [comment]
Thanks, a bundled dist would make it easier

but for the time being, changing https://github.com/pi0/bootstrap-vue/blob/master/.babelrc
from 

```json
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "transform-vue-jsx"
  ]
}
```
to
```json
{
  "presets": [
    "es2015"
  ],
  "plugins": [
    "transform-vue-jsx"
  ]
}
```

fixed my problem.

Could you explain what this `"modules": false` does?

**Comment by pi0** [comment]
@williamoliveira yep! that was exactly main issue [See Here](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/) :)
