### ISSUE TITLE
Why another component?

### ISSUE THREAD

**Issue by psi-4ward** [pi0/bootstrap-vue#2]
Hi,

why did you build own components instead of working with the guys from https://github.com/yuche/vue-strap ?

**Comment by pi0** [comment]
@psi-4ward hello and thanks for your interest :)  `yuche/vue-strap` was soo great and we where already using it. but we need a completly different road-map as there are many breaking changes in both Bootstrap **4** and Vue.Js **2** (just look at that repo's requirements)
