### ISSUE TITLE
navbar doesn't work

### ISSUE THREAD

**Issue by miquels** [pi0/bootstrap-vue#5]
I installed vue using vue-cli, with

```
   vue init webpack testproject   
   cd testproject   
   npm update
```

Then I added the vue2-bootstrap4 npm package as documented on https://www.npmjs.com/package/vue2-bootstrap4 ) .

```
   npm install --save-dev vue2-bootstrap4
```

I tried the button-group example. First it didn't work at all, I had to add bootstrap itself by doing

```
   npm install --save-dev bootstrap@4.0.0-alpha.5
```

.. and adding this to my .vue file:

```
   import 'bootstrap/dist/css/bootstrap.min.css'
```

The button-group example works. But the navbar example doesn't, the javascript console shows:

``
Vue warn: Failed to mount component: template or render function not defined.  (found in component <bNav>)
``

Mike.

**Comment by pi0** [comment]
@miquels Unfortunately `wapznw` made a crazy fork of this repo  called `bootstrap4-vue2`! Please use `bootstrap-vue` instead !
